### ISSUE TITLE
Chat content is not changing after changing username and useremail

### ISSUE THREAD

**Issue by viveklc** [rf1804/react-native-jivochat#2]
I have setup jivo chat by following the steps below:

1. Install jivochat plugin
2. Changed  widget_id and site_id in Loaction-> react-native-jivochat/android/src/main/assets/html/index_en.html
3. Calling jivochat like 

`import RNJivochat from 'react-native-jivochat';`

Call this function on a button press event:
```
var userName = 'Tester';
var userEmail = 'test@gmail.com';
RNJivochat.openJivoChat(userName, userEmail);
```
What is happening:

1. Chat window is opening
2. I am able to send message 

BUT if I am changing user credentials like userName and userEmail, it is still showing the previous user chat messages.

how can I acheive one to one chat?

**Comment by LucasMonteiro1** [comment]
Same problem

**Comment by rf1804** [comment]
Jivochat is for customer-operator chat, not one to one chat.
