### ISSUE TITLE
iOS Crash when call openJivoChat

### ISSUE THREAD

**Issue by WesleyFaveri** [rf1804/react-native-jivochat#3]
Error log: 
Exception 'Could not load NIB in bundle: 'NSBundle <App Path> (loaded)' with name 'JivoChatVC'' was thrown while invoking openJivoChat on target RNJivochat with params (
    "Tester",
    "test@gmail.com"
)

I have installed this package with pod, i need add anything or its a bug?

**Comment by joaozig** [comment]
same problem here

**Comment by rf1804** [comment]
Right Now i've not added podspec file so it does not support pods.
Kindly follow installation instructions https://github.com/rf1804/react-native-jivochat#ios

**Comment by WesleyFaveri** [comment]
Crash with manual install too :c

I really just need add libRNJivochat.a and RNJivochat.xcodeproj?

**Comment by WesleyFaveri** [comment]
I got it, install instructions is missing some reference like html folder and .xib file that you need add on .xcodeproj

**Comment by joaozig** [comment]
> I got it, install instructions is missing some reference like html folder and .xib file that you need add on .xcodeproj

Could you share what you did to fix?

**Comment by WesleyFaveri** [comment]
@joaozig You need open Jivo Project  Example on Xcode and compare with your Project, i think you missing add .xib file on project.
