### ISSUE TITLE
Error on openJivoChat

### ISSUE THREAD

**Issue by LucasMonteiro1** [rf1804/react-native-jivochat#4]
Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

**Comment by LucasMonteiro1** [comment]
https://stackoverflow.com/questions/3918517/calling-startactivity-from-outside-of-an-activity-context

**Comment by rf1804** [comment]
@LucasMonteiro1 Thanks for the PR

**Comment by LucasMonteiro1** [comment]
@rf1804 You’re welcome. I await release of version.
