### ISSUE TITLE
Gives error when run App -   error: reference to findViewById is ambiguous

### ISSUE THREAD

**Issue by Rafayel777** [rf1804/react-native-jivochat#6]
> Task :react-native-jivochat:compileDebugJavaWithJavac FAILED
\node_modules\react-native-jivochat\android\src\main\java\com\rf1804\jivochat\JivoActivity.java:30: error: reference to findViewById is ambiguous
        toolbar= (Toolbar) findViewById(R.id.toolbar);
                           ^
  both method findViewById(int) in Activity and method <T>findViewById(int) in AppCompatActivity match
  where T is a type-variable:
    T extends View declared in method <T>findViewById(int)
\node_modules\react-native-jivochat\android\src\main\java\com\rf1804\jivochat\JivoActivity.java:44: error: reference to findViewById is ambiguous
     jivoSdk = new JivoSdk((WebView) findViewById(R.id.webView), lang);
                                     ^
  both method findViewById(int) in Activity and method <T>findViewById(int) in AppCompatActivity match
  where T is a type-variable:
    T extends View declared in method <T>findViewById(int)
2 errors

**Comment by rf1804** [comment]
@Rafayel777 try invalidating cache/restart working fine for me

**Comment by evgenTraytyak** [comment]
@rf1804 hi, i've reproduced the same error..

```
/node_modules/react-native-jivochat/android/src/main/java/com/rf1804/jivochat/JivoActivity.java:30: error: reference to findViewById is ambiguous
        toolbar= (Toolbar) findViewById(R.id.toolbar);
                           ^
  both method findViewById(int) in Activity and method <T>findViewById(int) in AppCompatActivity match
  where T is a type-variable:
    T extends View declared in method <T>findViewById(int)
/Users/etraytyak/Documents/Work/GTApp/node_modules/react-native-jivochat/android/src/main/java/com/rf1804/jivochat/JivoActivity.java:44: error: reference to findViewById is ambiguous
     jivoSdk = new JivoSdk((WebView) findViewById(R.id.webView), lang);
                                     ^
  both method findViewById(int) in Activity and method <T>findViewById(int) in AppCompatActivity match
  where T is a type-variable:
    T extends View declared in method <T>findViewById(int)
2 errors

FAILURE: Build failed with an exception.
```

```
    "react-native-jivochat": "1.1.1",
    "react-native":  "0.59.3",
```

**Comment by evgenTraytyak** [comment]
https://github.com/rf1804/react-native-jivochat/pull/7
